//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CCSHealthFamilyWelfareDept.UPHEALTHNIC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="upswp_niveshmitraservicesSoap", Namespace="http://tempuri.org/")]
    public partial class upswp_niveshmitraservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WGetBasicDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WReturn_CUSID_STATUSOperationCompleted;
        
        private System.Threading.SendOrPostCallback WReturn_CUSID_PrintApplicationURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback WReturn_CUSID_ISLandPurchasedOperationCompleted;
        
        private System.Threading.SendOrPostCallback WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATOperationCompleted;
        
        private System.Threading.SendOrPostCallback WGetUBPaymentDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public upswp_niveshmitraservices() {
            this.Url = global::CCSHealthFamilyWelfareDept.Properties.Settings.Default.CCSHealthFamilyWelfareDept_UPHEALTHNIC_upswp_niveshmitraservices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WGetBasicDetailsCompletedEventHandler WGetBasicDetailsCompleted;
        
        /// <remarks/>
        public event WReturn_CUSID_STATUSCompletedEventHandler WReturn_CUSID_STATUSCompleted;
        
        /// <remarks/>
        public event WReturn_CUSID_PrintApplicationURLCompletedEventHandler WReturn_CUSID_PrintApplicationURLCompleted;
        
        /// <remarks/>
        public event WReturn_CUSID_ISLandPurchasedCompletedEventHandler WReturn_CUSID_ISLandPurchasedCompleted;
        
        /// <remarks/>
        public event WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompletedEventHandler WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompleted;
        
        /// <remarks/>
        public event WGetUBPaymentDetailsCompletedEventHandler WGetUBPaymentDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WGetBasicDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WGetBasicDetails(string ControlID, string UnitID, string ServiceID, string ProcessIndustryID, string passsalt) {
            object[] results = this.Invoke("WGetBasicDetails", new object[] {
                        ControlID,
                        UnitID,                       
                        ServiceID,
                        ProcessIndustryID,
                        
                        passsalt});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WGetBasicDetailsAsync(string ControlID, string UnitID, string ServiceID, string ProcessIndustryID, string passsalt) {
            this.WGetBasicDetailsAsync(ControlID, UnitID, ServiceID, ProcessIndustryID, passsalt, null);
        }
        
        /// <remarks/>
        public void WGetBasicDetailsAsync(string ControlID, string UnitID, string ServiceID, string ProcessIndustryID, string passsalt, object userState) {
            if ((this.WGetBasicDetailsOperationCompleted == null)) {
                this.WGetBasicDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWGetBasicDetailsOperationCompleted);
            }
            this.InvokeAsync("WGetBasicDetails", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        ProcessIndustryID,
                        passsalt}, this.WGetBasicDetailsOperationCompleted, userState);
        }
        
        private void OnWGetBasicDetailsOperationCompleted(object arg) {
            if ((this.WGetBasicDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WGetBasicDetailsCompleted(this, new WGetBasicDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WReturn_CUSID_STATUS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WReturn_CUSID_STATUS(
                    string ControlID, 
                    string UnitID, 
                    string ServiceID, 
                    string ProcessIndustryID, 
                    string ApplicationID, 
                    string Status_Code, 
                    string Remarks, 
                    string Pendancy_level, 
                    string Fee_Amount, 
                    string Fee_Status, 
                    string Transaction_ID, 
                    string Transaction_Date, 
                    string Transaction_Date_Time, 
                    string NOC_Certificate_Number, 
                    string NOC_URL, 
                    string ISNOC_URL_ActiveYesNO, 
                    string passsalt, 
                    string Request_ID, 
                    string Objection_Rejection_Code, 
                    string Is_Certificate_Valid_Life_Time, 
                    string Certificate_EXP_Date_DDMMYYYY, 
                    string D1, 
                    string D2, 
                    string D3, 
                    string D4, 
                    string D5, 
                    string D6, 
                    string D7) {
            object[] results = this.Invoke("WReturn_CUSID_STATUS", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        ProcessIndustryID,
                        ApplicationID,
                        Status_Code,
                        Remarks,
                        Pendancy_level,
                        Fee_Amount,
                        Fee_Status,
                        Transaction_ID,
                        Transaction_Date,
                        Transaction_Date_Time,
                        NOC_Certificate_Number,
                        NOC_URL,
                        ISNOC_URL_ActiveYesNO,
                        passsalt,
                        Request_ID,
                        Objection_Rejection_Code,
                        Is_Certificate_Valid_Life_Time,
                        Certificate_EXP_Date_DDMMYYYY,
                        D1,
                        D2,
                        D3,
                        D4,
                        D5,
                        D6,
                        D7});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WReturn_CUSID_STATUSAsync(
                    string ControlID, 
                    string UnitID, 
                    string ServiceID, 
                    string ProcessIndustryID, 
                    string ApplicationID, 
                    string Status_Code, 
                    string Remarks, 
                    string Pendancy_level, 
                    string Fee_Amount, 
                    string Fee_Status, 
                    string Transaction_ID, 
                    string Transaction_Date, 
                    string Transaction_Date_Time, 
                    string NOC_Certificate_Number, 
                    string NOC_URL, 
                    string ISNOC_URL_ActiveYesNO, 
                    string passsalt, 
                    string Request_ID, 
                    string Objection_Rejection_Code, 
                    string Is_Certificate_Valid_Life_Time, 
                    string Certificate_EXP_Date_DDMMYYYY, 
                    string D1, 
                    string D2, 
                    string D3, 
                    string D4, 
                    string D5, 
                    string D6, 
                    string D7) {
            this.WReturn_CUSID_STATUSAsync(ControlID, UnitID, ServiceID, ProcessIndustryID, ApplicationID, Status_Code, Remarks, Pendancy_level, Fee_Amount, Fee_Status, Transaction_ID, Transaction_Date, Transaction_Date_Time, NOC_Certificate_Number, NOC_URL, ISNOC_URL_ActiveYesNO, passsalt, Request_ID, Objection_Rejection_Code, Is_Certificate_Valid_Life_Time, Certificate_EXP_Date_DDMMYYYY, D1, D2, D3, D4, D5, D6, D7, null);
        }
        
        /// <remarks/>
        public void WReturn_CUSID_STATUSAsync(
                    string ControlID, 
                    string UnitID, 
                    string ServiceID, 
                    string ProcessIndustryID, 
                    string ApplicationID, 
                    string Status_Code, 
                    string Remarks, 
                    string Pendancy_level, 
                    string Fee_Amount, 
                    string Fee_Status, 
                    string Transaction_ID, 
                    string Transaction_Date, 
                    string Transaction_Date_Time, 
                    string NOC_Certificate_Number, 
                    string NOC_URL, 
                    string ISNOC_URL_ActiveYesNO, 
                    string passsalt, 
                    string Request_ID, 
                    string Objection_Rejection_Code, 
                    string Is_Certificate_Valid_Life_Time, 
                    string Certificate_EXP_Date_DDMMYYYY, 
                    string D1, 
                    string D2, 
                    string D3, 
                    string D4, 
                    string D5, 
                    string D6, 
                    string D7, 
                    object userState) {
            if ((this.WReturn_CUSID_STATUSOperationCompleted == null)) {
                this.WReturn_CUSID_STATUSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWReturn_CUSID_STATUSOperationCompleted);
            }
            this.InvokeAsync("WReturn_CUSID_STATUS", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        ProcessIndustryID,
                        ApplicationID,
                        Status_Code,
                        Remarks,
                        Pendancy_level,
                        Fee_Amount,
                        Fee_Status,
                        Transaction_ID,
                        Transaction_Date,
                        Transaction_Date_Time,
                        NOC_Certificate_Number,
                        NOC_URL,
                        ISNOC_URL_ActiveYesNO,
                        passsalt,
                        Request_ID,
                        Objection_Rejection_Code,
                        Is_Certificate_Valid_Life_Time,
                        Certificate_EXP_Date_DDMMYYYY,
                        D1,
                        D2,
                        D3,
                        D4,
                        D5,
                        D6,
                        D7}, this.WReturn_CUSID_STATUSOperationCompleted, userState);
        }
        
        private void OnWReturn_CUSID_STATUSOperationCompleted(object arg) {
            if ((this.WReturn_CUSID_STATUSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WReturn_CUSID_STATUSCompleted(this, new WReturn_CUSID_STATUSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WReturn_CUSID_PrintApplicationURL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WReturn_CUSID_PrintApplicationURL(string ControlID, string UnitID, string ServiceID, string PrintApplicationURL, string passsalt, string Request_ID) {
            object[] results = this.Invoke("WReturn_CUSID_PrintApplicationURL", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        PrintApplicationURL,
                        passsalt,
                        Request_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WReturn_CUSID_PrintApplicationURLAsync(string ControlID, string UnitID, string ServiceID, string PrintApplicationURL, string passsalt, string Request_ID) {
            this.WReturn_CUSID_PrintApplicationURLAsync(ControlID, UnitID, ServiceID, PrintApplicationURL, passsalt, Request_ID, null);
        }
        
        /// <remarks/>
        public void WReturn_CUSID_PrintApplicationURLAsync(string ControlID, string UnitID, string ServiceID, string PrintApplicationURL, string passsalt, string Request_ID, object userState) {
            if ((this.WReturn_CUSID_PrintApplicationURLOperationCompleted == null)) {
                this.WReturn_CUSID_PrintApplicationURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWReturn_CUSID_PrintApplicationURLOperationCompleted);
            }
            this.InvokeAsync("WReturn_CUSID_PrintApplicationURL", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        PrintApplicationURL,
                        passsalt,
                        Request_ID}, this.WReturn_CUSID_PrintApplicationURLOperationCompleted, userState);
        }
        
        private void OnWReturn_CUSID_PrintApplicationURLOperationCompleted(object arg) {
            if ((this.WReturn_CUSID_PrintApplicationURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WReturn_CUSID_PrintApplicationURLCompleted(this, new WReturn_CUSID_PrintApplicationURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WReturn_CUSID_ISLandPurchased", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WReturn_CUSID_ISLandPurchased(string ControlID, string UnitID, string ServiceID, string ISLandPurchasedYesNO, string passsalt) {
            object[] results = this.Invoke("WReturn_CUSID_ISLandPurchased", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        ISLandPurchasedYesNO,
                        passsalt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WReturn_CUSID_ISLandPurchasedAsync(string ControlID, string UnitID, string ServiceID, string ISLandPurchasedYesNO, string passsalt) {
            this.WReturn_CUSID_ISLandPurchasedAsync(ControlID, UnitID, ServiceID, ISLandPurchasedYesNO, passsalt, null);
        }
        
        /// <remarks/>
        public void WReturn_CUSID_ISLandPurchasedAsync(string ControlID, string UnitID, string ServiceID, string ISLandPurchasedYesNO, string passsalt, object userState) {
            if ((this.WReturn_CUSID_ISLandPurchasedOperationCompleted == null)) {
                this.WReturn_CUSID_ISLandPurchasedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWReturn_CUSID_ISLandPurchasedOperationCompleted);
            }
            this.InvokeAsync("WReturn_CUSID_ISLandPurchased", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        ISLandPurchasedYesNO,
                        passsalt}, this.WReturn_CUSID_ISLandPurchasedOperationCompleted, userState);
        }
        
        private void OnWReturn_CUSID_ISLandPurchasedOperationCompleted(object arg) {
            if ((this.WReturn_CUSID_ISLandPurchasedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WReturn_CUSID_ISLandPurchasedCompleted(this, new WReturn_CUSID_ISLandPurchasedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMAT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMAT(string strControlID, string strUnitID, string strServiceID, string ProcessIndustryID, string NOC_Certificate_Number, string base64, string MimeType, string passsalt, string Request_ID) {
            object[] results = this.Invoke("WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMAT", new object[] {
                        strControlID,
                        strUnitID,
                        strServiceID,
                        ProcessIndustryID,
                        NOC_Certificate_Number,
                        base64,
                        MimeType,
                        passsalt,
                        Request_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATAsync(string strControlID, string strUnitID, string strServiceID, string ProcessIndustryID, string NOC_Certificate_Number, string base64, string MimeType, string passsalt, string Request_ID) {
            this.WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATAsync(strControlID, strUnitID, strServiceID, ProcessIndustryID, NOC_Certificate_Number, base64, MimeType, passsalt, Request_ID, null);
        }
        
        /// <remarks/>
        public void WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATAsync(string strControlID, string strUnitID, string strServiceID, string ProcessIndustryID, string NOC_Certificate_Number, string base64, string MimeType, string passsalt, string Request_ID, object userState) {
            if ((this.WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATOperationCompleted == null)) {
                this.WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATOperationCompleted);
            }
            this.InvokeAsync("WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMAT", new object[] {
                        strControlID,
                        strUnitID,
                        strServiceID,
                        ProcessIndustryID,
                        NOC_Certificate_Number,
                        base64,
                        MimeType,
                        passsalt,
                        Request_ID}, this.WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATOperationCompleted, userState);
        }
        
        private void OnWReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATOperationCompleted(object arg) {
            if ((this.WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompleted(this, new WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WGetUBPaymentDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet WGetUBPaymentDetails(string ControlID, string UnitID, string ServiceID, string passsalt, string Request_ID) {
            object[] results = this.Invoke("WGetUBPaymentDetails", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        passsalt,
                        Request_ID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void WGetUBPaymentDetailsAsync(string ControlID, string UnitID, string ServiceID, string passsalt, string Request_ID) {
            this.WGetUBPaymentDetailsAsync(ControlID, UnitID, ServiceID, passsalt, Request_ID, null);
        }
        
        /// <remarks/>
        public void WGetUBPaymentDetailsAsync(string ControlID, string UnitID, string ServiceID, string passsalt, string Request_ID, object userState) {
            if ((this.WGetUBPaymentDetailsOperationCompleted == null)) {
                this.WGetUBPaymentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWGetUBPaymentDetailsOperationCompleted);
            }
            this.InvokeAsync("WGetUBPaymentDetails", new object[] {
                        ControlID,
                        UnitID,
                        ServiceID,
                        passsalt,
                        Request_ID}, this.WGetUBPaymentDetailsOperationCompleted, userState);
        }
        
        private void OnWGetUBPaymentDetailsOperationCompleted(object arg) {
            if ((this.WGetUBPaymentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WGetUBPaymentDetailsCompleted(this, new WGetUBPaymentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WGetBasicDetailsCompletedEventHandler(object sender, WGetBasicDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WGetBasicDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WGetBasicDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WReturn_CUSID_STATUSCompletedEventHandler(object sender, WReturn_CUSID_STATUSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WReturn_CUSID_STATUSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WReturn_CUSID_STATUSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WReturn_CUSID_PrintApplicationURLCompletedEventHandler(object sender, WReturn_CUSID_PrintApplicationURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WReturn_CUSID_PrintApplicationURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WReturn_CUSID_PrintApplicationURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WReturn_CUSID_ISLandPurchasedCompletedEventHandler(object sender, WReturn_CUSID_ISLandPurchasedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WReturn_CUSID_ISLandPurchasedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WReturn_CUSID_ISLandPurchasedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompletedEventHandler(object sender, WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WReturn_CUSID_Entrepreneur_NOC_IN_BINARYFORMATCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void WGetUBPaymentDetailsCompletedEventHandler(object sender, WGetUBPaymentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WGetUBPaymentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WGetUBPaymentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591